//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRole
    {
        public AccountRole()
        {
            this.Account = new HashSet<Account>();
        }
    
        public int Role_ID { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public int Law_ID { get; set; }
    
        public virtual AccountLaw AccountLaw { get; set; }
        public virtual ICollection<Account> Account { get; set; }
    }
}
