//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Module = new HashSet<Module>();
            this.AccountRole = new HashSet<AccountRole>();
        }
    
        public int Account_ID { get; set; }
        public string Email { get; set; }
        public bool isSuperUser { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<Module> Module { get; set; }
        public virtual ICollection<AccountRole> AccountRole { get; set; }
    }
}
