//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentCode
    {
        public int AssignmentCode_ID { get; set; }
        public int EC { get; set; }
        public string Description { get; set; }
        public int Module_ID { get; set; }
        public Nullable<int> PrevModule_ID { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
