//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Competence
    {
        public Competence()
        {
            this.Level = new HashSet<Level>();
            this.Module = new HashSet<Module>();
        }

        [Key]
        public int Competence_ID { get; set; }
        [Required(ErrorMessage = "Titel mag niet leeg zijn")]

        public string Title { get; set; }
        [Required(ErrorMessage = "Omschrijving Kort mag niet leeg zijn")]
        public string Definition_Short { get; set; }
        [Required(ErrorMessage = "Omschrijving Lang heeft doelen nodig")]
        public string Definition_Long { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }

        public virtual ICollection<Level> Level { get; set; }
        public virtual ICollection<Module> Module { get; set; }
    }
}
