//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LearningTool
    {
        public LearningTool()
        {
            this.Module = new HashSet<Module>();
        }
    
        public int LearnTool_ID { get; set; }
        public Nullable<int> PrevLearnTool_ID { get; set; }
        [Required]
        public string Description { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual ICollection<Module> Module { get; set; }
    }
}
