//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearnCourse
    {
        public LearnCourse()
        {
            this.Module = new HashSet<Module>();
        }
    
        public int LearnCourse_ID { get; set; }
        public string Title { get; set; }
        public string Definition { get; set; }
        public string LearnCourseCode { get; set; }
        public string level { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int Phasing_ID { get; set; }
    
        public virtual ICollection<Module> Module { get; set; }
        public virtual Phasing Phasing { get; set; }
    }
}
