//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleStudyPhasingBlock
    {
        public int Module_ID { get; set; }
        public int Study_ID { get; set; }
        public int Phasing_ID { get; set; }
        public int Block_ID { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual Module Module { get; set; }
        public virtual Phasing Phasing { get; set; }
        public virtual Study Study { get; set; }
    }
}
