//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Level = new HashSet<Level>();
            this.ModelActivity = new HashSet<ModelActivity>();
            this.Program = new HashSet<Program>();
            this.Theme1 = new HashSet<Theme>();
        }
    
        public int Module_ID { get; set; }
        public string Title { get; set; }
        public string Course_Code { get; set; }
        public string EC { get; set; }
        public string Method { get; set; }
        public string Entry_Level { get; set; }
        public int Workload { get; set; }
        public string GradeType { get; set; }
        public string Organization { get; set; }
        public string Definition_Short { get; set; }
        public string Definition_Long { get; set; }
        public string Foreknowledge { get; set; }
        public int Competence_ID { get; set; }
        public int Theme_ID { get; set; }
        public int LearnCourse_ID { get; set; }
        public int ModuleYear_ID { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Competence Competence { get; set; }
        public virtual ExamCode ExamCode { get; set; }
        public virtual GradeType GradeType1 { get; set; }
        public virtual LearnCourse LearnCourse { get; set; }
        public virtual LearnGoal LearnGoal { get; set; }
        public virtual LearningTool LearningTool { get; set; }
        public virtual ICollection<Level> Level { get; set; }
        public virtual ICollection<ModelActivity> ModelActivity { get; set; }
        public virtual WeekSchedule WeekSchedule { get; set; }
        public virtual ModuleHistory ModuleHistory { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual ICollection<Program> Program { get; set; }
        public virtual ICollection<Theme> Theme1 { get; set; }
    }
}
