//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workform
    {
        public Workform()
        {
            this.ModelWithWorkform = new HashSet<ModelWithWorkform>();
        }
    
        public int Workform_ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> PrevWorkform_ID { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual ICollection<ModelWithWorkform> ModelWithWorkform { get; set; }
    }
}
